import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
      <a 
        href="https://wa.me/524424469991?text=Hola, vengo de su página web." 
        target="_blank"
        className="fixed bottom-6 right-6 z-50 bg-emerald-500 p-4 rounded-full shadow-xl hover:scale-110 transition-transform animate-bounce"
      >
        <img src="/icons/WhatsappIcon.svg" className="w-8 h-8" />
      </a></body>
      
    </html>
  );
}
